#!/bin/bash

# Get the actual commit hash
commit_hash=$(git rev-parse --short HEAD)

# Get the branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Create the actual build hash with commit hash and branch name
build_hash="${commit_hash}-${branch_name}"

# Update build_hash.json without committing it
echo "{\"build_hash\": \"$build_hash\"}" > ethicapp/backend/build_hash.json
