#!/bin/bash

# Get the branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Placeholder for the commit hash
build_hash="PENDING-${branch_name}"

# Write the placeholder to build_hash.json
echo "{\"build_hash\": \"$build_hash\"}" > ethicapp/backend/build_hash.json

# Stage build_hash.json for the commit
git add ethicapp/backend/build_hash.json
