# --------------------------------------------------------------------------------------------------
# Project configuration file for ESLint.
# --------------------------------------------------------------------------------------------------

---
env:
  browser: true
  es2021: true
  node: true
  jquery: true
  # mocha: true #* should uncomment when JS tests are implemented
extends:
  - eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - angular
globals:
  # Defining globals for linter (otherwise, they will trigger the "no-undef" rule with importing)
  # Libraries under ethicapp/frontent/assets/libs
  angular: true # angular.min.js
  rangy: true # rangy-core.min.js
  PDFJS: true # pdf.min.js
  TextLayerBuilder: true # textlayerbuilder.js
  UAParser: true # ua-parser.min.js
  saveCsv: true # save-csv.min.js
rules:
  quotes:
    - error
    - double
    - avoidEscape: true

  no-duplicate-imports:
    - error

  indent:
    - error
    - 4

  max-len:
    - warn
    - 100
    - ignoreComments: false # doc comments should be correctly wrapped
    - ignoreTrailingComments: true # tolerance for trailing inline comments

  linebreak-style:
    - error
    - unix

  semi:
    - error

  no-extra-semi:
    - error

  key-spacing:
    - error
    - align: value
      beforeColon: false

  func-style:
    - warn
    - declaration
    - allowArrowFunctions: false

  no-redeclare:
    - warn # default: error

  no-unused-vars:
    - warn # default: error

  no-undef:
    - warn # default: error

  no-useless-escape: 0
