# --------------------------------------------------------------------------------------------------
# Project configuration file for ESLint.
# --------------------------------------------------------------------------------------------------

---
env:
  browser: true
  es2021: true
  node: true
  jquery: true
  # mocha: true #* for when tests are implemented
extends:
  - eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - angular
globals:
  angular: true
rules:
  quotes:
    - error
    - double
    - avoidEscape: true

  no-duplicate-imports:
    - error

  indent:
    - error
    - 4

  max-len:
    - warn
    - 100
    - ignoreComments: false # doc comments should be correctly wrapped
    - ignoreTrailingComments: true # flexibility for trailing inline comments

  linebreak-style:
    - error
    - unix

  semi:
    - error

  no-extra-semi:
    - error

  key-spacing:
    - error
    - align: value
      beforeColon: false

  func-style:
    - warn
    - expression

  no-redeclare:
    - warn # default: error

  no-unused-vars:
    - warn # default: error

  no-undef:
    - warn # default: error

  no-useless-escape: 0
