FROM node:18

WORKDIR /home/app

# Copiar package.json y package-lock.json
# Como el contexto ya es ./ethicapp, no se necesita el prefijo ./ethicapp/
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Instalar dependencias adicionales que podrían ser necesarias
RUN npm install pg sequelize sequelize-cli --save

# Copiar el resto de la aplicación
# Como el contexto ya es ./ethicapp, copiamos todo (.)
COPY . ./

# Configurar variables de entorno
ENV NODE_ENV=test \
    NODE_PORT=3100 \
    ALLOWED_ORIGINS="*" \
    DB_HOST=ethicapp-test-postgres \
    DB_PORT=5432 \
    DB_NAME=ethicapp_test \
    DB_USER_NAME=postgres \
    DB_USER_PASSWORD=postgres

# Exponer el puerto
EXPOSE 3100

# Comando para iniciar la aplicación en modo prueba
CMD ["npm", "run", "start"]