FROM node:18

WORKDIR /home/app

# Copiar package.json y package-lock.json
COPY ./ethicapp/package*.json ./

# Instalar dependencias
RUN npm install

# Instalar dependencias adicionales que podrían ser necesarias
RUN npm install pg --save

# Copiar el resto de la aplicación
COPY ./ethicapp ./

# Copiar el archivo de configuración personalizado
COPY ./ethicapp/backend/config/postgres-connection.js ./backend/config/passwords.js

# Exponer el puerto
EXPOSE 3100

# Comando para iniciar la aplicación en modo prueba
CMD ["node", "app.js"]
