version: "3.9"

networks:
  default:

services:
  nginx:
    build:
      context: web-nginx/
    ports:
      - "${NGINX_PORT}:80"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      NODE_PORT: ${NODE_PORT}
      NODE_SERVER: node
    networks:
      default:
    volumes:
      - shared-volume:/usr/share/nginx/:rw
      - shared-volume-admin:/usr/share/nginx/admin:rw

volumes:
  shared-volume:
  shared-volume-admin:
