# --------------------------------------------------------------------------------------------------
# DEVELOPMENT docker-compose.
# --------------------------------------------------------------------------------------------------

version: "3.9"

networks:
  default:

services:
  # ---------------------- Node web app ---------------------- #
  node:
    build:
      context: ethicapp/
      dockerfile: Dockerfile.image-rebuild
      args:
        NODE_VERSION: ${NODE_VERSION}
    environment:
      NODE_ENV: release
      NODE_PORT: ${NODE_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    restart: "no"
    networks:
      default:
    ports:
      - "${NODE_PORT}:${NODE_PORT}"