# --------------------------------------------------------------------------------------------------
# DEVELOPMENT docker-compose.
# --------------------------------------------------------------------------------------------------

version: "3.9"

networks:
  default:

services:
  # ---------------------- Node web app ---------------------- #
  ethicapp:
    build:
      context: ethicapp/
      dockerfile: Dockerfile.image-rebuild
      args:
        ETHICAPP_NODE_VERSION: ${NODE_VERSION}
    environment:
      NODE_ENV: release
      ETHICAPP_NODE_PORT: ${ETHICAPP_NODE_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    restart: "no"
    networks:
      default:
    ports:
      - "${ETHICAPP_NODE_PORT}:${ETHICAPP_NODE_PORT}"