# --------------------------------------------------------------------------------------------------
# NGINX configuration for deployment with docker-compose.
# --------------------------------------------------------------------------------------------------

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile   on;
    gzip       on;

    include      /etc/nginx/mime.types;
    types
    {
        application/javascript mjs;
    }
    access_log   /var/log/nginx/access.log;
    error_log    /var/log/nginx/error.log;


    upstream ethicapp {
        ip_hash;
        server $ETHICAPP_HOSTNAME:$ETHICAPP_NODE_PORT;
    }

    server {
	listen 80;
        server_name localhost;

        location /assets/ {
            root /usr/share/nginx;
            autoindex on;
            access_log /var/log/nginx/assets_access.log;
            error_log /var/log/nginx/assets_error.log;
        }

        location ^~ /admin {
            alias /usr/share/nginx/admin/build;
            try_files $uri $uri/ /admin/index.html;
        }

        location ~* \.(svg|png|jpg|css|json|min.js|pdf)$ {
            try_files $uri @node;
        }

        location / {           
            try_files $uri @node;
        }

        location @node {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass       http://ethicapp;

            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
