CREATE ROLE ${DB_USER_NAME} WITH
LOGIN PASSWORD '${DB_USER_PASSWORD}'
NOCREATEDB
NOSUPERUSER;

CREATE DATABASE ${DB_NAME} WITH
OWNER ${DB_USER_NAME}
ENCODING 'UTF8'
LC_COLLATE 'C.UTF-8'
LC_CTYPE 'C.UTF-8'
CONNECTION LIMIT -1;

CREATE DATABASE ${DB_TEST_NAME} WITH
OWNER ${DB_USER_NAME}
ENCODING 'UTF8'
LC_COLLATE 'C.UTF-8'
LC_CTYPE 'C.UTF-8'
CONNECTION LIMIT -1;
