FROM python:3.9-slim

WORKDIR /app/content-analysis

COPY requirements-content-analysis.txt requirements.txt

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app/content-analysis:$PYTHONPATH


EXPOSE 5000

CMD ["python", "app.py"]
